### ISSUE TITLE
Include variable functions

### ISSUE THREAD

**Issue by mikeb333** [fzipp/gocyclo#19]
I noticed that functions declared as variables are not included.  It would be nice if they were. We use variable functions a lot for testability and mocking.

**Comment by trajber** [comment]
I opened a [PR](https://github.com/fzipp/gocyclo/pull/27) for this. It seems to be working.
Can you give it a go if you are still looking for this change, please ?

**Comment by fzipp** [comment]
Fixed by 6ee3d8d3fc8ab4f7ccdc5f023639d4ccba87ea8c
