### ISSUE TITLE
Add flag to skip tests

### ISSUE THREAD

**Issue by AnthonyMBonafide** [fzipp/gocyclo#33]
Add a flag which will exclude testing code from the generated report. 

I think it is useful to be able to optionally exclude tests from the report. I am suggesting this be a flag and optional since the exclusion or inclusion of test source code is dependant on the developer(s) or project maintainer(s) and this would give flexibility to whatever they decide.

**Comment by sebastianst** [comment]
Yes, please merge #31

**Comment by fzipp** [comment]
Fixed by 4a36b7d43972d5dd35bc5204f7314dcb8cc848e4: -ignore flag added
