### ISSUE TITLE
Provide Changelog

### ISSUE THREAD

**Issue by Teddy34** [fzipp/gocyclo#35]
Hey!

My build failed today because of the change to the installation path of the project in 0.2.0 release.

I cannot create a branch to propose a pull request, so here's a template of changelog for you

```
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [0.3.0] - 2020-10-17
### Added

### Changed

### Removed

## [0.2.0] - 2020-10-17
### Added

### Changed
- Breaking: installation changed to `go get github.com/fzipp/gocyclo/cmd/gocyclo`

### Removed

```

Best regards and thanks for your lib.

**Comment by fzipp** [comment]
Thanks, I have added a changelog.

I recommend using specific versions of gocyclo in your CI setup. This should be easier now that gocyclo is a Go module and has tagged versions.
